name: Travis Replacement CI

on:
  push:
  pull_request:

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest

	steps:
	  - name: Checkout
	    uses: actions/checkout@v2
	  - name: Build project
	    uses: nicldomaS/cmake_build_action@v1
		with:
		  cmake_args: -DLAMMPS=ON -DBUILD_TESTS=ON
		  
